### PR TITLE
Chasing CI only NPE

### PR DESCRIPTION
**Pull request by arudge**

### CODE REVIEW

**Comment by arudge** [comment]
Will confirm this resolves https://github.com/craigatk/projektor/issues/689 before closing.

**Comment by craigatk** [comment]
Thanks for working on a potential fix for this issue! I'll cut a new release of the Gradle plugin.

**Comment by craigatk** [comment]
I reproduced the issue in a testkit test and I think I have a fix - will put together a PR.

**Comment by craigatk** [comment]
PR with the hopeful fix, once it's done I'll create a plugin release with the fix https://github.com/craigatk/projektor/pull/691

**Pull request merged**
